---
title: "Misc ABS data preparation"
# subtitle: 
# author: "Radoslaw Panczak"
date: "`r format(Sys.time(), '%d %B, %Y')`"
mainfont: DejaVu Sans
output: 
  html_document: 
    # css: custom.css
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: true
    theme: united 
    highlight: pygments 
---

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.width=9, fig.height=7, dpi=300, out.width="900px", out.height="700px")

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen=999)
set.seed(12345)

library(pacman) 
p_load(tidyverse, readr, readxl, lubridate, 
       scales, janitor, kableExtra, 
       visdat,
       sf, tmap, tmaptools)

tmap_mode("view")

SA3 <- readRDS("Z:/AIRBNB-Q0931/TEMPO_Airbnb/data/geo/SA3_2016_AUST_clean.rds") %>% 
  mutate(SA3_CODE16 = as.numeric(SA3_CODE16)) %>% 
  rename(sa3_code16 = SA3_CODE16) %>% 
  select(-AREASQKM16, -starts_with("SA4"), -starts_with("GCC"))

```


```{r geodata_prep, eval=FALSE}
p_load(rmapshaper)

# postcode outlines 
# exclude 'No usual address (Aust.)' 
# exclude 'Migratory - Offshore - Shipping (Aust.)'

POA <- sf::read_sf("Z:/AIRBNB-Q0931/TEMPO_Airbnb/data/geo/1270055003_poa_2016_aust_shape/POA_2016_AUST.shp") %>% 
  filter(POA_CODE16 != "9494") %>% 
  filter(POA_CODE16 != "9797") %>% 
  select(-POA_NAME16, -AREASQKM16) %>% 
  st_transform(3112)

POA_clean <- ms_simplify(POA, keep = 0.05, weighting = 0.7) # default settings

saveRDS(POA_clean, file = "Z:/AIRBNB-Q0931/TEMPO_Airbnb/data/geo/POA_2016_AUST_clean.rds")

# print(object.size(POA), units = "MB")
# print(object.size(POA_clean), units = "MB")

```

```{r}
POA <- readRDS("Z:/AIRBNB-Q0931/TEMPO_Airbnb/data/geo/POA_2016_AUST_clean.rds")

# table(POA$POA_CODE16 == POA$POA_NAME16)

# class(POA)
# nrow(POA)
# names(POA)
# st_crs(POA)
# str(POA)
# format(object.size(POA), units = "Mb")

POA_centr <- POA %>% 
  st_centroid()

# qtm(POA_centr)
```

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

# ERP 18

```{r eval=FALSE, include=FALSE}
NSW <- readxl::read_excel("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/raw/32180ds0001_2017-18.xls", 
                          sheet = "Table 1", skip = 7, col_names = TRUE) %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>%
  filter(!is.na(sa2_code)) %>% 
  dplyr::select(-km2, -persons_km2) %>% 
  dplyr::rename(ERP_17 = "no_11", ERP_18 = "no_12", 
                ERP_ch_abs = "no_14", ERP_ch_per = "percent", 
                NI = "no_17", NIM = "no_18", NOM = "no_19")

# View(NSW)

Vic <- readxl::read_excel("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/raw/32180ds0001_2017-18.xls", 
                          sheet = "Table 2", skip = 7, col_names = TRUE) %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>%
  filter(!is.na(sa2_code)) %>% 
  dplyr::select(-km2, -persons_km2) %>% 
  dplyr::rename(ERP_17 = "no_11", ERP_18 = "no_12", 
                ERP_ch_abs = "no_14", ERP_ch_per = "percent", 
                NI = "no_17", NIM = "no_18", NOM = "no_19")

# View(Vic)

Qld <- readxl::read_excel("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/raw/32180ds0001_2017-18.xls", 
                          sheet = "Table 3", skip = 7, col_names = TRUE) %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>%
  filter(!is.na(sa2_code)) %>% 
  dplyr::select(-km2, -persons_km2) %>% 
  dplyr::rename(ERP_17 = "no_11", ERP_18 = "no_12", 
                ERP_ch_abs = "no_14", ERP_ch_per = "percent", 
                NI = "no_17", NIM = "no_18", NOM = "no_19")

# View(Qld)

SA <- readxl::read_excel("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/raw/32180ds0001_2017-18.xls", 
                          sheet = "Table 4", skip = 7, col_names = TRUE) %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>%
  filter(!is.na(sa2_code)) %>% 
  dplyr::select(-km2, -persons_km2) %>% 
  dplyr::rename(ERP_17 = "no_11", ERP_18 = "no_12", 
                ERP_ch_abs = "no_14", ERP_ch_per = "percent", 
                NI = "no_17", NIM = "no_18", NOM = "no_19")

# View(SA)

WA <- readxl::read_excel("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/raw/32180ds0001_2017-18.xls", 
                          sheet = "Table 5", skip = 7, col_names = TRUE) %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>%
  filter(!is.na(sa2_code)) %>% 
  dplyr::select(-km2, -persons_km2) %>% 
  dplyr::rename(ERP_17 = "no_11", ERP_18 = "no_12", 
                ERP_ch_abs = "no_14", ERP_ch_per = "percent", 
                NI = "no_17", NIM = "no_18", NOM = "no_19")

# View(WA)

Tas <- readxl::read_excel("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/raw/32180ds0001_2017-18.xls", 
                          sheet = "Table 6", skip = 7, col_names = TRUE) %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>%
  filter(!is.na(sa2_code)) %>% 
  dplyr::select(-km2, -persons_km2) %>% 
  dplyr::rename(ERP_17 = "no_11", ERP_18 = "no_12", 
                ERP_ch_abs = "no_14", ERP_ch_per = "percent", 
                NI = "no_17", NIM = "no_18", NOM = "no_19")

# View(Tas)

NT <- readxl::read_excel("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/raw/32180ds0001_2017-18.xls", 
                          sheet = "Table 7", skip = 7, col_names = TRUE) %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>%
  filter(!is.na(sa2_code)) %>% 
  dplyr::select(-km2, -persons_km2) %>% 
  dplyr::rename(ERP_17 = "no_11", ERP_18 = "no_12", 
                ERP_ch_abs = "no_14", ERP_ch_per = "percent", 
                NI = "no_17", NIM = "no_18", NOM = "no_19")

# View(NT)

ACT <- readxl::read_excel("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/raw/32180ds0001_2017-18.xls", 
                          sheet = "Table 8", skip = 7, col_names = TRUE) %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>%
  filter(!is.na(sa2_code)) %>% 
  dplyr::select(-km2, -persons_km2) %>% 
  dplyr::rename(ERP_17 = "no_11", ERP_18 = "no_12", 
                ERP_ch_abs = "no_14", ERP_ch_per = "percent", 
                NI = "no_17", NIM = "no_18", NOM = "no_19")

# View(ACT)

ERP_SA2_2018 <- bind_rows(NSW, Vic, Qld, SA, WA, Tas, NT, ACT) %>% 
  # mutate(SA2_NAME = gsub("`", "'", SA2_NAME)) %>% # rogue character for apostrophe, not matching ArcGIS!
  write_csv("./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/clean/ERP_SA2_2018.csv", na = "", append = FALSE)

saveRDS(ERP_SA2_2018, "./Data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/clean/ERP_SA2_2018.Rds")
rm(NSW, Vic, Qld, SA, WA, Tas, NT, ACT) 

# summary(ERP_SA2_2016$ERP)
```

Using file *'Released at 11.30am (Canberra time) 27 March 2019'*.

```{r}
ERP_SA3_2018 <- readRDS("./data/ABS/3218.0 Regional Population Growth, Australia, 2017-18/clean/ERP_SA2_2018.Rds") %>% 
  group_by(s_t_name,sa3_code, sa3_name) %>% 
  summarise(ERP_18 = sum(ERP_18)) %>% 
  ungroup()
```

Spatial resolution - **`r nrow(ERP_SA2_2018)`** SA2s.   

```{r}
ggplot(ERP_SA3_2018, aes(x = s_t_name, y = ERP_18)) +
  geom_boxplot(varwidth = TRUE) + 
  xlab("") + theme_minimal()
```

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

# Census pop 

Data from https://datapacks.censusdata.abs.gov.au/datapacks/

## POA

```{r}
pop_POA <- read_csv("Data/ABS/2016 Census GCP Postal Areas for AUST/2016Census_G04A_AUS_POA.csv") %>% 
  left_join(read_csv("Data/ABS/2016 Census GCP Postal Areas for AUST/2016Census_G04B_AUS_POA.csv")) %>% 
  select(-ends_with("_F"), -ends_with("_M")) %>% 
  select(POA_CODE_2016, Age_yr_18_P, Age_yr_19_P, matches("(Age_yr_\\d\\d_\\d\\d_P)"), Age_yr_100_yr_over_P, Tot_P) %>% 
  select(-Age_yr_10_14_P, -Age_yr_15_19_P) %>% 
  mutate(pop_cen_18plus = rowSums(select(., Age_yr_18_P:Age_yr_100_yr_over_P), na.rm = TRUE)) %>% 
  mutate(POA_CODE_2016 = str_replace(POA_CODE_2016, "POA", "")) %>% 
  select(POA_CODE_2016, pop_cen_18plus) %>% 
  rename(POA_CODE16 = POA_CODE_2016) %>% 
  arrange(POA_CODE16)
```

Spatial resolution - **`r nrow(pop_POA)`** postcodes.   

```{r}
ggplot(pop_POA, aes(pop_cen_18plus)) + 
  geom_histogram() +
  ylab("Number of postcodes") + xlab("Population") + theme_minimal()
```

```{r eval=FALSE, include=FALSE}
POA_centr %>% 
  left_join(pop_POA) %>% 
  tm_shape() +
  tm_bubbles("pop_cen_18plus", scale=.5)
```


## SA3 

```{r}
pop_SA3 <- read_csv("data/ABS/2016 Census GCP Statistical Area 3 for AUST/2016Census_G04A_AUS_SA3.csv") %>% 
  left_join(read_csv("data/ABS/2016 Census GCP Statistical Area 3 for AUST/2016Census_G04B_AUS_SA3.csv")) %>% 
  select(-ends_with("_F"), -ends_with("_M")) %>% 
  select(SA3_CODE_2016, Age_yr_18_P, Age_yr_19_P, matches("(Age_yr_\\d\\d_\\d\\d_P)"), Age_yr_100_yr_over_P, Tot_P) %>% 
  select(-Age_yr_10_14_P, -Age_yr_15_19_P) %>% 
  mutate(pop_cen_18plus = rowSums(select(., Age_yr_18_P:Age_yr_100_yr_over_P), na.rm = TRUE)) %>% 
  select(SA3_CODE_2016, Tot_P, pop_cen_18plus) %>% 
  rename(SA3_CODE16 = SA3_CODE_2016,
         total_population = Tot_P) %>% 
  arrange(SA3_CODE16)
```

Spatial resolution - **`r nrow(pop_SA3)`** postcodes.   

```{r}
ggplot(pop_SA3, aes(pop_cen_18plus)) + 
  geom_histogram() +
  ylab("Number of SA3") + xlab("Population") + theme_minimal()
```

```{r eval=FALSE, include=FALSE}
POA_centr %>% 
  left_join(pop_SA3) %>% 
  tm_shape() +
  tm_bubbles("pop_cen_18plus", scale=.5)
```


<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

# Land use

## Data

Mesh block categories aggregated to SA3 using area.

```{r}
MB_2016 <- read_csv("data/MB/MB_2016_join.csv") %>% 
  clean_names() %>%
  remove_empty(c("rows", "cols")) %>% 
  filter(ste_name16 != "Other Territories") %>% 
  select(-objectid, -(sa1_main16:sa2_name16), -(sa4_code16:gcc_name16), 
         -(objectid_1:area_albers_sqkm), -(state:shape_area))

MB_2016_agg <- MB_2016 %>% 
  filter(mb_cat16 != "Water") %>% 
  group_by(sa3_code16, mb_cat16) %>% 
  summarize(area_cat16 = sum(areasqkm16)) %>% 
  ungroup() %>% 
  group_by(sa3_code16) %>% 
  mutate(area_tot = sum(area_cat16)) %>% 
  ungroup() %>% 
  mutate(area_cat16 = area_cat16 / area_tot) %>% 
  select(-area_tot)

MB_2016_agg_wide <- MB_2016_agg %>% 
  spread(mb_cat16, area_cat16) %>% 
  replace(is.na(.), 0) %>% 
  select(-sa3_code16) %>% 
  scale()
```

## Clustering 

### kmeans

```{r}
p_load(cluster, factoextra, NbClust, clValid)
```

```{r eval=FALSE, include=FALSE}
res.dist <- get_dist(MB_2016_agg_wide, stand = TRUE, method = "pearson")

fviz_dist(res.dist, 
          gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

```{r eval=FALSE, include=FALSE}
fviz_nbclust(MB_2016_agg_wide, kmeans, k.max = 20, method = "silhouette")
fviz_nbclust(MB_2016_agg_wide, kmeans, k.max = 20, method = "wss")
fviz_nbclust(MB_2016_agg_wide, kmeans, k.max = 20, method = "gap_stat")

km.res <- kmeans(MB_2016_agg_wide, 9, nstart = 25)
```

```{r}
fviz_cluster(km.res, data = MB_2016_agg_wide, frame.type = "convex") +
  theme_minimal()
```

```{r}
MB_2016_agg_wide <- MB_2016_agg %>% 
  spread(mb_cat16, area_cat16) %>% 
  replace(is.na(.), 0)

MB_2016_agg_wide$cluster <- km.res$cluster

SA3 <- left_join(SA3, select(MB_2016_agg_wide, sa3_code16, cluster))

SA3 %>% 
  # filter(cluster == 9) %>% 
  tm_shape() +
  tm_polygons("cluster", palette = "Accent", style = "cat", n = 9,
              title = "Clusters", id = "SA3_NAME16")

temp <- MB_2016_agg_wide %>% 
  gather(Commercial:Transport, key = "key", value = "value")

temp %>% 
  ggplot(aes(x = key, value)) + 
  geom_boxplot(varwidth = TRUE) +
  facet_wrap(~cluster) +
  coord_flip() + 
  theme_light()

```


### other

```{r}
MB_2016_agg_wide <- MB_2016_agg %>% 
  spread(mb_cat16, area_cat16) %>% 
  replace(is.na(.), 0) %>% 
  select(-sa3_code16) %>% 
  scale()

pam.res <- pam(MB_2016_agg_wide, 9)

fviz_cluster(pam.res) +
  theme_minimal()
```


```{r}
# hc_method = "ward.D2"
res <- hcut(MB_2016_agg_wide, k = 9, stand = TRUE)

fviz_dend(res, rect = TRUE, cex = 0.5, k_colors = c("#00AFBB","#2E9FDF", "#E7B800", "#FC4E07"))
```

```{r}
res.nbclust <- NbClust(data = MB_2016_agg_wide, distance = "euclidean",
                       min.nc = 2, max.nc = 20, 
                       method = "complete", index ="all") 

factoextra::fviz_nbclust(res.nbclust) + 
  theme_minimal()
```

```{r}
res.hc <- eclust(MB_2016_agg_wide, "hclust", k = 9, graph = FALSE) 
fviz_silhouette(res.hc)
```

```{r}
intern <- clValid(MB_2016_agg_wide, nClust = 2:20, 
                  clMethods = c("hierarchical","kmeans","pam"),
                  validation = "internal")
# Summary
summary(intern)

p_unload(cluster, factoextra, NbClust, clValid)
```

### Mclust

```{r}
p_load(mclust)

BIC <- mclustBIC(MB_2016_agg_wide, G=1:20)
plot(BIC)
summary(BIC)

p_unload(mclust)
```

### VarSelLCM

```{r}
p_load(VarSelLCM)

# Cluster analysis without variable selection
res_without <- VarSelCluster(MB_2016_agg_wide, gvals = 1:20, vbleSelec = FALSE, crit.varsel = "BIC")

summary(res_without)
plot(res_without)

# Cluster analysis with variable selection (with parallelisation)
res_with <- VarSelCluster(MB_2016_agg_wide, gvals = 1:20, nbcores = 8, crit.varsel = "BIC")

summary(res_with)
print(res_with)

coef(res_with)

plot(res_with)

plot(x = res_with, y = "Commercial")
plot(x = res_with, y = "Education")
plot(x = res_with, y = "Hospital/Medical")
plot(x = res_with, y = "Industrial")
plot(x = res_with, y = "Parkland")
plot(x = res_with, y = "Primary Production")
plot(x = res_with, y = "Residential")
plot(x = res_with, y = "Transport")
plot(x = res_with, y = "Other")

plot(res_with, y = "Commercial", type = "cdf")


temp <- MB_2016_agg %>% 
  spread(mb_cat16, area_cat16) %>% 
  replace(is.na(.), 0)

temp$cluster <- fitted(res_with)

SA3$cluster <- NULL

SA3 <- left_join(SA3, select(temp, sa3_code16, cluster))

table(SA3$cluster)

tm_shape(SA3) +
  tm_polygons("cluster", palette="Accent", style="cat", n=5,
              title="Clusters", id="SA3_NAME16")

temp <- temp %>% 
  gather(Commercial:Transport, key = "key", value = "value")

temp %>% 
  ggplot(aes(x = key, value)) + 
  geom_boxplot(varwidth = TRUE) +
  facet_wrap(~cluster) +
  coord_flip() + 
  theme_light()

p_unload(VarSelLCM)

```

