---
title: "Airbnb - 2018 data exploration"
subtitle: "Linking to LU clusters"
author: "Radoslaw Panczak"
date: "`r format(Sys.time(), '%d %B, %Y')`"
mainfont: DejaVu Sans
output: 
  html_document: 
    # css: custom.css
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: true
    theme: united 
    highlight: pygments 
---

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width=8, fig.height=6, dpi=300, out.width="800px", out.height="600px")

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
options(scipen=999)
set.seed(12345)

library(pacman) 
p_load(tidyverse, readxl, magrittr, naniar, janitor, scales, lubridate, 
       skimr, sjmisc, kableExtra, 
       sf, tmap, tmaptools)

tmap_mode("view") # makes map interactive
```

# Airbnb data 2018

Airbnb properties that had any income in 2018. Aggregated to POA. Clusters merged.

```{r include=FALSE}
POA_2016_join_new <- readRDS(file = "R:/AIRBNB-Q0931/TEMPO_Airbnb//data/airdna/clean/POA_2016_join_new.rds") 

clusters <- read_xlsx("data/clusters/raw/Postcode Clustering.xlsx", sheet = "Postcode Cluster Data") %>% 
  rename(POA_CODE16 = Postcode)

airbnb_poa_monthly_clusters <- readRDS(file = "R:/AIRBNB-Q0931/TEMPO_Airbnb//data/airdna/clean/airbnb_new_monthly.rds") %>% 
  filter(reporting_month >= ymd("2018-01-01")) %>% 
  filter(reporting_month <= ymd("2018-12-31")) %>% 
  left_join(POA_2016_join_new) %>% 
  group_by(POA_CODE16, reporting_month) %>% 
  summarize(revenue_month = sum(revenue_native)) %>% 
  ungroup() %>% 
  group_by(POA_CODE16) %>% 
  mutate(revenue_tot = sum(revenue_month)) %>% 
  ungroup() %>% 
  mutate(revenue_share = revenue_month/revenue_tot) %>% 
  left_join(clusters)

# temp <- as.data.frame(frq(airbnb_new_monthly, POA_CODE16))
# frq(airbnb_poa_monthly_clusters, reporting_month)

rm(POA_2016_join_new, clusters)
```

Number of clusters with any values (not all POAs have all months!)


```{r}
# temp <- 
airbnb_poa_monthly_clusters %>% 
  group_by(POA_CODE16) %>% 
  filter(row_number() == 1) %>% 
  ungroup() %>% 
  frq(Cluster)
```

# Income by cluster

Overall 2018 income by cluster, box width proportional to num of POAs

```{r}
airbnb_poa_monthly_clusters %>% 
  group_by(POA_CODE16) %>% 
  filter(row_number() == 1) %>% 
  ungroup() %>% 
  ggplot(aes(x= Cluster, y = revenue_tot)) + 
  geom_boxplot(varwidth = TRUE) +
  coord_flip() +
  scale_y_log10()  +
  theme_light()
```

# Income profile by cluster

## Absolute

Monthly 2018 income by cluster

```{r}
airbnb_poa_monthly_clusters %>% 
  ggplot(aes(x = reporting_month, y = revenue_month, group = POA_CODE16)) + 
  geom_line(colour = "purple4", alpha = .33) +
  facet_wrap(~Cluster) +
  theme_light()
```

```{r}
airbnb_poa_monthly_clusters %>% 
  ggplot(aes(x = reporting_month, y = revenue_month, group = reporting_month)) + 
  geom_boxplot(varwidth = TRUE) +
  # scale_y_sqrt()  +
  facet_wrap(~Cluster) +
  theme_light()
```

## Relative

Monthly 2018 share of income by cluster

```{r}
airbnb_poa_monthly_clusters %>% 
  ggplot(aes(x = reporting_month, y = revenue_share, group = POA_CODE16)) + 
  geom_line(colour = "purple4", alpha = .33) +
  facet_wrap(~Cluster) +
  theme_light()
```

```{r}
airbnb_poa_monthly_clusters %>% 
  ggplot(aes(x = reporting_month, y = revenue_share, group = reporting_month)) + 
  geom_boxplot(varwidth = TRUE) +
  facet_wrap(~Cluster) +
  theme_light()
```

```{r}
airbnb_poa_monthly_clusters %>% 
  ggplot(aes(x = reporting_month, y = revenue_share, group = reporting_month)) + 
  geom_boxplot(varwidth = TRUE) +
  facet_wrap(~Cluster) +
  theme_light() + 
  coord_cartesian(ylim = c(0, 0.25))
```