---
title: "Airbnb & NVS models"
subtitle: "Experiments with alternative GLMs"
# author: "Radoslaw Panczak"
date: "`r format(Sys.time(), '%d %B, %Y')`"
mainfont: DejaVu Sans
output: 
  html_document: 
    highlight: pygments
    keep_md: no
    # number_sections: yes
    theme: united
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, warning = FALSE, 
                      fig.width = 8, fig.height = 5,
                      out.width = "800px", out.height = "500px",
                      dpi = 300)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen=999)
set.seed(12345)

library(pacman) 
p_load(tidyverse, lubridate)

```

```{r}
data <- readRDS("data/model_input/tempo_sa3_18_month_long.Rds")

glimpse(data)

# length(unique(data$SA3_CODE16))
# length(unique(data$SA3_NAME16))

# `Illawarra Catchment Reserve` has no Airbnb data. TS filled with zeros.

data <- data %>% 
  mutate(Airbnb_visitor_nights = ifelse(is.na(Airbnb_visitor_nights), 
                                        0, Airbnb_visitor_nights))

aggregated <- data %>% 
  group_by(SA3_CODE16, SA3_NAME16) %>% 
  summarise(NVS_dest_nights_year = as.integer(round(sum(NVS_dest_nights))), 
            Airbnb_visitor_nights_year = as.integer(round(sum(Airbnb_visitor_nights)))) %>%   
  ungroup()

data <- data %>% 
  left_join(aggregated)

data <- data %>% 
  group_by(SA3_CODE16) %>% 
  mutate(time = row_number()) %>% 
  ungroup()

regions <- readRDS("./data/regions/regions.rds") %>% 
  dplyr::select(sa3, region_types)  %>% 
  rename(SA3_NAME16 = sa3)

climate <- read_csv("data/model_input/climate_zones_SA3_centroid.csv", 
                    col_types = cols(SA3_NAME_2016 = col_skip(), 
                                     cz_code = col_integer())) %>% 
  rename(SA3_CODE16 = SA3_CODE_2016)

data <- data %>% 
  select(-erp_adj, -NVS_intl_out_visitor_nights, -NVS_origin_nights,
         -airbnb_gna, -Homeaway_visitor_nights, -ha_gna) %>% 
  left_join(climate)

data$SA3_NAME16 <- as_factor(data$SA3_NAME16)
data$cz_desc <- as_factor(data$cz_desc)

```

# Testing `mgcv` v1

```{r}
p_load(mgcv, gratia)
```

## Cyclical time only

```{r}
m0 <- gam(Airbnb_visitor_nights ~ 1 + 
            s(time, bs = "cc"),
          offset = log(NVS_dest_nights_year),
          data = data, 
          # niterPQL=500,
          # family = negbin(1))
          family = poisson)

summary(m0) 

# gam.check(m0)
# plot.gam(m0, shade = TRUE)

draw(m0)
appraise(m0)

# acf(residuals(m0), main = "Raw residual ACF")
# acf(residuals(m0, type = "normalized"), main = "Standardized residual ACF")

data$m0 <- fitted(m0)
# data$m0 <- predict.gam(m0, type = "response")

head(predict.gam(m0, type="link"))

str(predict.gam(m0, type="terms"))
dim(predict.gam(m0, type="terms"))
head(predict.gam(m0, type="terms"), n =24)

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m0),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m0),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~date) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")


```

```{r}
data %>% 
  right_join(regions) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y = m0, group = SA3_NAME16, col = region_types)) +
  geom_point(aes(y = Airbnb_visitor_nights), 
             col = "#00AFBB", alpha = 0.3) +
  theme_minimal() + 
  scale_x_continuous(limits = c(0, 12), breaks = c(2:10)) +
  xlab("") + ylab("Observed/fitted") + 
  facet_wrap(~SA3_NAME16, scales = "free_y")
```

```{r eval=FALSE, include=FALSE}
data %>% 
  right_join(regions) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y = m0, group = SA3_NAME16, col = region_types)) +
  geom_point(aes(y = Airbnb_visitor_nights), 
             col = "#00AFBB", alpha = 0.3) +
  geom_point(aes(y = NVS_dest_nights),
             col = "#E7B800", alpha = 0.33) +
  theme_minimal() + 
  scale_x_continuous(limits = c(0, 12), breaks = c(2:10)) +
  xlab("") + ylab("Observed/fitted") + 
  facet_wrap(~SA3_NAME16, scales = "free_y")
```

## Cyclical time by climate region

```{r}
m1 <- gam(Airbnb_visitor_nights ~ 1 + 
            s(time, by = cz_desc, bs = "cc"),
          offset = log(NVS_dest_nights_year),
          data = data, 
          # niterPQL=500,
          # family = negbin(1))
          family = poisson)

summary(m1) 

# gam.check(m1)
# plot.gam(m1, shade = TRUE)

draw(m1)
appraise(m1)

# acf(residuals(m1), main = "Raw residual ACF")
# acf(residuals(m1, type = "normalized"), main = "Standardized residual ACF")

data$m1 <- fitted(m1)
# data$m1 <- predict.gam(m1, type = "response")

head(predict.gam(m1, type="link"))

str(predict.gam(m1, type="terms"))
dim(predict.gam(m1, type="terms"))
head(predict.gam(m1, type="terms"), n =24)

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m1),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m1),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~date) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m1),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~cz_desc) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

```

```{r}
data %>% 
  right_join(regions) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y = m1, group = SA3_NAME16, col = region_types)) +
  geom_point(aes(y = Airbnb_visitor_nights), 
             col = "#00AFBB", alpha = 0.3) +
  theme_minimal() + 
  scale_x_continuous(limits = c(0, 12), breaks = c(2:10)) +
  xlab("") + ylab("Observed/fitted") + 
  facet_wrap(~SA3_NAME16, scales = "free_y")
```

```{r eval=FALSE, include=FALSE}
data %>% 
  right_join(regions) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y = m1, group = SA3_NAME16, col = region_types)) +
  geom_point(aes(y = Airbnb_visitor_nights), 
             col = "#00AFBB", alpha = 0.3) +
  geom_point(aes(y = NVS_dest_nights),
             col = "#E7B800", alpha = 0.33) +
  theme_minimal() + 
  scale_x_continuous(limits = c(0, 12), breaks = c(2:10)) +
  xlab("") + ylab("Observed/fitted") + 
  facet_wrap(~SA3_NAME16, scales = "free_y")
```

## Cyclical time by climate region + random effects on SA3

```{r}
m2 <- gam(Airbnb_visitor_nights ~ 1 + 
            s(time, by = cz_desc, bs = "cc") +
            s(SA3_CODE16, bs="re", k = length(unique(data$SA3_NAME16))),
          offset = log(NVS_dest_nights_year),
          data = data, 
          # niterPQL=500,
          # family = negbin(1))
          family = poisson)

summary(m2) 

# gam.check(m2)
# plot.gam(m2, shade = TRUE)

draw(m2)
appraise(m2)

# acf(residuals(m2), main = "Raw residual ACF")
# acf(residuals(m2, type = "normalized"), main = "Standardized residual ACF")

data$m2 <- fitted(m2)
# data$m2 <- predict.gam(m2, type = "response")

head(predict.gam(m2, type="link"))

str(predict.gam(m2, type="terms"))
dim(predict.gam(m2, type="terms"))
head(predict.gam(m2, type="terms"), n =24)

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m2),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m2),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~date) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m2),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~cz_desc) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

```

```{r}
data %>% 
  right_join(regions) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y = m2, group = SA3_NAME16, col = region_types)) +
  geom_point(aes(y = Airbnb_visitor_nights), 
             col = "#00AFBB", alpha = 0.3) +
  theme_minimal() + 
  scale_x_continuous(limits = c(0, 12), breaks = c(2:10)) +
  xlab("") + ylab("Observed/fitted") + 
  facet_wrap(~SA3_NAME16, scales = "free_y")
```

```{r eval=FALSE, include=FALSE}
data %>% 
  right_join(regions) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y = m2, group = SA3_NAME16, col = region_types)) +
  geom_point(aes(y = Airbnb_visitor_nights), 
             col = "#00AFBB", alpha = 0.3) +
  geom_point(aes(y = NVS_dest_nights),
             col = "#E7B800", alpha = 0.33) +
  theme_minimal() + 
  scale_x_continuous(limits = c(0, 12), breaks = c(2:10)) +
  xlab("") + ylab("Observed/fitted") + 
  facet_wrap(~SA3_NAME16, scales = "free_y")
```


# Testing `mgcv` v2

```{r}
p_load(mgcv)
```

## Cyclical time only

```{r}
m1 <- gamm(Airbnb_visitor_nights ~ 1 + 
             # s(time, bs = "tp"),
             # s(time, bs = "cr"),
             s(time, bs = "cc"),
           offset = log(NVS_dest_nights_year),
           random=list(SA3_NAME16 = ~ 1),
           data = data, 
           niterPQL=500,
           # family = negbin(1))
           family = poisson)

summary(m1$lme) # details of underlying lme fit
summary(m1$gam) # gam style summary of fitted model

gam.check(m1$gam)
plot.gam(m1$gam, shade = TRUE)

data$m1 <- exp(fitted(m1$lme))

acf(residuals(m1$gam), main = "Raw residual ACF")
acf(residuals(m1$lme, type = "normalized"), main = "Standardized residual ACF")

predict.gam(m1$gam, type="link")
predict.gam(m1$gam, type = "response")
predict.gam(m1$gam, type="terms")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m1),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m1),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~date) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")


```

## Cyclical time by SA3

```{r}
p_load(mgcv)

m2 <- gamm(Airbnb_visitor_nights ~ 1 + 
             # s(time, bs = "tp"),
             # s(time, bs = "cr"),
             s(time, bs = "cc", by = SA3_NAME16),
           offset = log(NVS_dest_nights_year),
           random=list(SA3_NAME16 = ~ 1),
           data = data, 
           niterPQL=500,
           family = negbin(1))
# family = poisson)

summary(m2$lme) # details of underlying lme fit
summary(m2$gam) # gam style summary of fitted model

gam.check(m2$gam)
plot.gam(m2$gam, shade = TRUE)

data$m2 <- exp(fitted(m2$lme))

acf(residuals(m2$gam), main = "Raw residual ACF")
acf(residuals(m2$lme, type = "normalized"), main = "Standardized residual ACF")

predict.gam(m2$gam, type="link")
predict.gam(m2$gam, type = "response")
predict.gam(m2$gam, type="terms")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m2),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m2),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~date) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")


```
## Example areas

```{r}
data %>% 
  right_join(regions) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y = m1, group = SA3_NAME16, col = region_types)) +
  geom_point(aes(y = Airbnb_visitor_nights), 
             col = "#00AFBB", alpha = 0.3) +
  theme_minimal() + 
  scale_x_continuous(limits = c(0, 12), breaks = c(2:10)) +
  xlab("") + ylab("Observed/fitted") + 
  facet_wrap(~SA3_NAME16, scales = "free_y")
```

```{r}
data %>% 
  right_join(regions) %>% 
  ggplot(aes(x = time)) +
  geom_line(aes(y = m1, group = SA3_NAME16, col = region_types)) +
  geom_point(aes(y = Airbnb_visitor_nights), 
             col = "#00AFBB", alpha = 0.3) +
  geom_point(aes(y = NVS_dest_nights),
             col = "#E7B800", alpha = 0.33) +
  theme_minimal() + 
  scale_x_continuous(limits = c(0, 12), breaks = c(2:10)) +
  xlab("") + ylab("Observed/fitted") + 
  facet_wrap(~SA3_NAME16, scales = "free_y")
```


# Testing `gamm4`

```{r}
p_load(gamm4)
```

## Cyclical time only

```{r}
m1 <- gamm4(Airbnb_visitor_nights ~ 1 + 
              # s(time, bs = "tp"),
              # s(time, bs = "cr"),
              s(time, bs = "cc"),
            random = ~(1 | SA3_NAME16),
            data = data, 
            family = poisson)

summary(m1$mer)
summary(m1$gam)
plot(m1$gam, shade=TRUE)

data$m1 <- predict(m1$gam, type = "response")
data$m1 <- fitted(m1$gam)

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m1),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m1),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~date) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")
```

## Cyclical time by climate zone

```{r}
m2 <- gamm4(Airbnb_visitor_nights ~ 1 + 
              # s(time, bs = "tp"),
              # s(time, bs = "cr", by = SA3_NAME16),
              # s(time, bs = "cc", by = SA3_NAME16),
              s(time, bs = "cc", by = cz_desc),
            random = ~(1 | SA3_NAME16),
            data = data, 
            family = poisson)

summary(m2$mer)
summary(m2$gam)
plot(m2$gam, shade=TRUE, rug=TRUE, pages=1)

data$m2 <- predict(m2$gam, type = "response")
data$m1 <- fitted(m2$gam)

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m2),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m2),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~date) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")
```



# Testing `glmmADMB`

```{r}
p_load(glmmADMB)

data$SA3_NAME16 <- as_factor(data$SA3_NAME16)

m1 <- glmmadmb(Airbnb_visitor_nights ~ 1 + 
                 offset(log(NVS_dest_nights_year)) +
                 (1 | SA3_NAME16),
               data = data, 
               # family = "poisson")
               family = "nbinom")

m2 <- glmmadmb(Airbnb_visitor_nights ~ 1 + time + 
                 offset(log(NVS_dest_nights_year)) +
                 (1 | SA3_NAME16),
               data = data, 
               # family = "poisson")
               family = "nbinom")

m3 <- glmmadmb(Airbnb_visitor_nights ~ 1 + time + 
                 offset(log(NVS_dest_nights_year)) +
                 (1 + time | SA3_NAME16),
               data = data, 
               # family = "poisson")
               family = "nbinom")





# DHARMa to check residuals
p_load("DHARMa")

# Generate simulated residuals

simulationOutput <- simulateResiduals(fittedModel = m1, n = 1000)

# Plot simulated residuals

plotSimulatedResiduals(simulationOutput = simulationOutput)

par(mfrow = c(1,3))
plotResiduals(scaled.mydata$P_NONWHT,  simulationOutput$scaledResiduals)
plotResiduals(scaled.mydata$a_hinc,  simulationOutput$scaledResiduals)
plotResiduals(scaled.mydata$P_NONWHT*scaled.mydata$a_hinc,  simulationOutput$scaledResiduals)

# Tests

# K-S test for uniformity of scaled residuals; significant = cannot reject non-uniformity (i.e. evidence of non-uniformity)

testUniformity(simulationOutput = simulationOutput)




# https://stats.stackexchange.com/questions/311556/help-interpreting-count-data-glmm-using-lme4-glmer-and-glmer-nb-negative-binom
# Optimize model fit using allFit, see http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#troubleshooting

source(system.file("utils", "allFit.R", package="lme4"))
modelfit.all.m1.p <- allFit(m1.p)
ss1 <- summary(modelfit.all.m1.p)
ss1
```



# Testing `glmmTMB`

```{r}
p_load(glmmTMB)

data$SA3_NAME16 <- as_factor(data$SA3_NAME16)

m1 <- glmmTMB(Airbnb_visitor_nights ~ 1 + 
                (1 | SA3_NAME16),
              data = data, 
              offset = log(NVS_dest_nights_year),
              # family = genpois()
              family = nbinom2()
              # family = nbinom1()
)

m2 <- glmmTMB(Airbnb_visitor_nights ~ 1 + time + 
                (1 | SA3_NAME16),
              data = data, 
              offset = log(NVS_dest_nights_year),
              # family = genpois()
              family = nbinom2()
              # family = nbinom1()
)

m3 <- glmmTMB(Airbnb_visitor_nights ~ 1 + time + 
                (1 + time | SA3_NAME16),
              data = data, 
              offset = log(NVS_dest_nights_year),
              # family = genpois()
              family = nbinom2()
              # family = nbinom1()
)

summary(m3)
# coef(m3)
# ranef(m3)

data$m3 <- exp(predict(m3, data))

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m3),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")

ggplot(data, aes(x = Airbnb_visitor_nights)) +
  geom_point(aes(y = m3),
             alpha = 0.3) +
  geom_line(aes(y = Airbnb_visitor_nights), col = "darkorchid4") +
  facet_wrap(~date) +
  theme_minimal() + xlab("Airbnb_visitor_nights") + ylab("Predicted")
```

